version: '3'

services:

  postgres:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend-challenge
    networks:
      - backend-challenge
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    networks:
      - backend-challenge
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: password

  app:
    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: Dockerfile

    volumes:
      - .:/app/
      - /app/node_modules

    container_name: backend-challenge-agiletech
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend-challenge
    depends_on:
      - postgres
    environment:
      APP_VERSION: ${APP_VERSION}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/backend-challenge
      JWT_SECRET: ${JWT_SECRET}

networks:
  backend-challenge:
    driver: bridge
